### ISSUE TITLE
Missing lib/cmds/admin directory

### ISSUE THREAD

**Issue by rguiu** [kristianoye/kmud#2]
I tried to run the mud following the instructions:

```
 npm install
./startmud --setup
./startmud
```
But I get:

```
Error in method 'create': ENOENT: no such file or directory, scandir .../kmud/lib/cmds/admin/'
Error: ENOENT: no such file or directory, scandir '.../kmud/lib/cmds/admin/'
    at Object.fs.readdirSync (fs.js:921:18)
```

**Comment by kristianoye** [comment]
I left it in a bad state but I have been trying to get back to it (in the middle of a backyard project right now).

**Comment by kristianoye** [comment]
Added placeholders to ensure the missing directories get created.  I was able to clone a fresh copy, start the MUD, and log in... but there are a heap of other errors (ls command hangs, etc).
