### ISSUE TITLE
Mud client issues (assumption on cr/lf)

### ISSUE THREAD

**Issue by LimpingNinja** [kristianoye/kmud#4]
When connecting with certain mud clients (GMud32 for example) the socket code appears to make some assumptions about line-endings. When logging on if I type "limpingninja" it returns: "limpingninj" and in single character selection menus ([y/n] it never gets input) as it appears to be pulling len-2 and probably only getting a single CR or similar. I plan on testing a little today just to see where the failure is, but haven't dug too deeply yet.

**Comment by LimpingNinja** [comment]
It appears to be as I expected:

RanvierTelnet.js
On entry, databuf (toString()) = "Test\n"

The loop on line 252-262 checks for \n, pushing each char to the buffer databuf. This leads to databuf being: "Test".


```
            // If multiple commands were sent \r\n separated in the same packet process
            // them separately. Some client auto-connect features do this
            let bucket = [];
            for (let i = 0; i < inputlen; i++) {
                if (databuf[i] === 3) { // ctrl-c 
                    continue; //eat it
                }
                if (databuf[i] !== 10) { // \n
                    bucket.push(databuf[i]);
                } else {
                    this.input(Buffer.from(bucket));
                    bucket = [];
                }
            }

            if (bucket.length) {
                this.input(Buffer.from(bucket));
            }
```

When this is then parsed for negotiations, in input the string is chopped by one character:
Line 471 of RanvierTelnet.js:         

`this.emit('data', cleanbuf.slice(0, cleanlen - 1)); `

**Comment by LimpingNinja** [comment]
Easy patch:

```
--- a/src/network/clients/telnet/RanvierTelnet.js
+++ b/src/network/clients/telnet/RanvierTelnet.js
@@ -254,6 +254,9 @@ class TelnetSocket extends EventEmitter {
@@ -254,6 +254,9 @@ class TelnetSocket extends EventEmitter {
                 if (databuf[i] === 3) { // ctrl-c
                     continue; //eat it
                 }
+                if (databuf[i] === 13) { // \r
+                    continue; //eat it
+                }
                 if (databuf[i] === 13) { // ctrl-c
                     continue; //eat it
                 }
@@ -471,7 +474,7 @@ class TelnetSocket extends EventEmitter {
          * @event TelnetSocket#data
          * @param {Buffer} data
          */
-        this.emit('data', cleanbuf.slice(0, cleanlen - 1));
+        this.emit('data', cleanbuf);
     }
 }
```

Additio
The other option is to test for \r as last character on line 474. This of course leaves a dilemma in how to handle the rest of the assumptions on \r\n with telnet IAC since GMud actually - I will test those out later

**Comment by LimpingNinja** [comment]
Here is a proper pull request from the original project that has never been absorbed into the original or forks: [RanvierMUD/ranvier-telnet pull#5 Fix: Handle any combination or order of CR and LF as command delimiters](https://github.com/RanvierMUD/ranvier-telnet/pull/5/commits/7c2fb2a0b268ab705d543d8b7bb7497faa8a14af)

**Comment by kristianoye** [comment]
I tried integrating the change but I ran into some double-buffering in the MUD shell from my Linux box (which is firing the data event twice... presumably once for CR and once for LF?).  That is with me only playing with the patch for 30 seconds though so I will have to reserve comments for now).  Also, CTRL-C still borks the connection on a Linux telnet session.  Non-HTTP clients are lower priority for me though (although super handy for debugging).

**Comment by LimpingNinja** [comment]
I did some tests, it seems like you tried my patch vs the upstream pull request; I'll fork you and drop the upstream pull request in and then do some tests to verify. 

* Linux telnet
* OSX telnet
* Windows telnet
* GMud
* Mudlet
* MushClient
* TinTin

I'll test all of the above and if it works drop you a pull request. I get it's lower priority - but since even now the ubiquity of text clients in mudding is high, it'll be good to have in.

>> Offtopic: Trying to create a base-lib do you have any clean driver applies mapping so I can baseline?

**Comment by LimpingNinja** [comment]
PR #5 should satisfy and I've done all tests with the exception of TinTin.

**Comment by kristianoye** [comment]
Thanks for that.  The merge looks good.  I haven't done any widespread client testing (I briefly tested with zMUD but am used to Linux telnet).  I will work on trying to better document the supported driver applies but I've been trying to re-think my own lib's master object and configuration files (which are kind of a hot mess right now).  I am kind of new to the whole npm ecosystem or I probably would have split the mudlib and the game driver into separate packages.
